### ISSUE TITLE
Managing State Demo

### ISSUE THREAD

**Issue by howarddierking** [howarddierking/building-restful-services#54]
Architecture 
- Node Web API
- Rethinkdb database

Steps to get infrastructure setup
- [x] Get vanilla rethink db up and running
- [x] Figure out how to load data into the database - manually load the files
- [x] Create custom Docker image that automatically loads the files
- [x] Publish to dockerhub
- [x] Launch app on Node image (or build one?) - link to rethink container
- [ ] expose single endpoint to get small bit of data from rethinkdb
